language: python

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests (report "this directory" i.e. "dot")
script:
    - pytest --cov-report term-missing --cov=.

env:
 - CODECOV_TOKEN=$CODECOV_TOKEN

after_success:
 - codecov

